version: "3"
services:
  go_redis_api:
    build:
      context: .
      dockerfile: ./Dockerfile
    working_dir: /app
    ports:
      - "8080:8080"
    depends_on:
      - redis
    links:
      - redis
    container_name: go_redis_api
    env_file:
      - .env
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    container_name: redis
